Update linter.yml

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,29 +1,24 @@
-name: VersionRelease
+name: cpp-linter
 
-# Controls when the workflow will run
-on:
-	push:
-  		paths-ignore: "docs/**"
-	pull_request:
-  		paths-ignore: "docs/**"
+on: 
+  - pull_request
+  - push
+
 jobs:
-	cpp-linter:
-	runs-on: ubuntu-latest
-		steps:
-			- uses: actions/checkout@v3
-			- name: Linter
-				id: linter
-				continue-on-error: true
-				uses: cpp-linter/cpp-linter-action@v2
-				env:
-					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
-				with:
-					style: file
-					files-changed-only: false
+  cpp-linter:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+          extra-args: -std=gnu11 -Wall -Werror
 
-			- name: Fail fast?!
-				if: steps.linter.outputs.checks-failed != 0
-				run: | 
-					echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
-			# for actual deployment 
-			# run: exit 1
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: echo "Some files failed the linting checks!"
+        # for actual deployment
+        # run: exit 1
